hydra:
  run:
    dir: 'train_experiment/${now:%Y-%m-%d}/${now:%H-%M}'
  output_subdir: 'yamls'

dataset_module:
  batch_size: 128
  num_workers: 12
  dataset_root: "mock_dataset"
  use_all_augmentations: false
  resize_augmentation_keys: null
  augmentation_keys: null
  nn_input_image_resolution: 64

train_module:
  lr: 0.001
  base_model: 'resnet50'
  number_of_cordinates: 386

training:
  wandb_project: "face-morphing"
  wandb_name: "sanity-check"
  with_gpu: true
  max_epochs: 50
  early_stop:
    monitor: "val_loss"
    patience: 100000
    mode: "min"
